//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Scripts_Utils_UIDragClickWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Scripts.Utils.UIDragClick), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("AddDragStart", AddDragStart);
		L.RegFunction("AddDrag", AddDrag);
		L.RegFunction("AddDragEnd", AddDragEnd);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddDragStart(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			Scripts.Utils.UIDragClick obj = (Scripts.Utils.UIDragClick)ToLua.CheckObject<Scripts.Utils.UIDragClick>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			LuaTable arg1 = ToLua.CheckLuaTable(L, 3);
			LuaFunction arg2 = ToLua.CheckLuaFunction(L, 4);
			obj.AddDragStart(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddDrag(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			Scripts.Utils.UIDragClick obj = (Scripts.Utils.UIDragClick)ToLua.CheckObject<Scripts.Utils.UIDragClick>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			LuaTable arg1 = ToLua.CheckLuaTable(L, 3);
			LuaFunction arg2 = ToLua.CheckLuaFunction(L, 4);
			obj.AddDrag(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddDragEnd(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			Scripts.Utils.UIDragClick obj = (Scripts.Utils.UIDragClick)ToLua.CheckObject<Scripts.Utils.UIDragClick>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			LuaTable arg1 = ToLua.CheckLuaTable(L, 3);
			LuaFunction arg2 = ToLua.CheckLuaFunction(L, 4);
			obj.AddDragEnd(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

