//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Scripts_Utils_MouseClickWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Scripts.Utils.MouseClick), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("AddMouseDownClick", AddMouseDownClick);
		L.RegFunction("RemoveMouseDownClick", RemoveMouseDownClick);
		L.RegFunction("AddMouseUpClick", AddMouseUpClick);
		L.RegFunction("RemoveMouseUpClick", RemoveMouseUpClick);
		L.RegFunction("AddMouseUpAsButtonClick", AddMouseUpAsButtonClick);
		L.RegFunction("RemoveMouseUpAsButtonClick", RemoveMouseUpAsButtonClick);
		L.RegFunction("AddMouseDragClick", AddMouseDragClick);
		L.RegFunction("RemoveMouseDragClick", RemoveMouseDragClick);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddMouseDownClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			Scripts.Utils.MouseClick obj = (Scripts.Utils.MouseClick)ToLua.CheckObject<Scripts.Utils.MouseClick>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			LuaTable arg1 = ToLua.CheckLuaTable(L, 3);
			LuaFunction arg2 = ToLua.CheckLuaFunction(L, 4);
			obj.AddMouseDownClick(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveMouseDownClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Scripts.Utils.MouseClick obj = (Scripts.Utils.MouseClick)ToLua.CheckObject<Scripts.Utils.MouseClick>(L, 1);
			obj.RemoveMouseDownClick();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddMouseUpClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			Scripts.Utils.MouseClick obj = (Scripts.Utils.MouseClick)ToLua.CheckObject<Scripts.Utils.MouseClick>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			LuaTable arg1 = ToLua.CheckLuaTable(L, 3);
			LuaFunction arg2 = ToLua.CheckLuaFunction(L, 4);
			obj.AddMouseUpClick(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveMouseUpClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Scripts.Utils.MouseClick obj = (Scripts.Utils.MouseClick)ToLua.CheckObject<Scripts.Utils.MouseClick>(L, 1);
			obj.RemoveMouseUpClick();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddMouseUpAsButtonClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			Scripts.Utils.MouseClick obj = (Scripts.Utils.MouseClick)ToLua.CheckObject<Scripts.Utils.MouseClick>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			LuaTable arg1 = ToLua.CheckLuaTable(L, 3);
			LuaFunction arg2 = ToLua.CheckLuaFunction(L, 4);
			obj.AddMouseUpAsButtonClick(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveMouseUpAsButtonClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Scripts.Utils.MouseClick obj = (Scripts.Utils.MouseClick)ToLua.CheckObject<Scripts.Utils.MouseClick>(L, 1);
			obj.RemoveMouseUpAsButtonClick();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddMouseDragClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			Scripts.Utils.MouseClick obj = (Scripts.Utils.MouseClick)ToLua.CheckObject<Scripts.Utils.MouseClick>(L, 1);
			UnityEngine.GameObject arg0 = (UnityEngine.GameObject)ToLua.CheckObject(L, 2, typeof(UnityEngine.GameObject));
			LuaTable arg1 = ToLua.CheckLuaTable(L, 3);
			LuaFunction arg2 = ToLua.CheckLuaFunction(L, 4);
			obj.AddMouseDragClick(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveMouseDragClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			Scripts.Utils.MouseClick obj = (Scripts.Utils.MouseClick)ToLua.CheckObject<Scripts.Utils.MouseClick>(L, 1);
			obj.RemoveMouseDragClick();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

